### ISSUE TITLE
Comment please, or description variable

### ISSUE THREAD

**Issue by andrewyatesg** [cornell-dti/research-connect#74]
https://github.com/cornell-dti/research-connect/blob/7565a0ea9395f54faec4d85d36ae71b389283236/api/labAdmins.js#L25

What does the error code 2 denote??

**Comment by abagh0703** [comment]
See https://www.npmjs.com/package/debug, debug is a tool to print and only have it show when debugging, instead of doing console.log since that shows up in production. Not sure what the proper coding practice is for commenting statements that are libraries/packages.

**Comment by SamChou19815** [comment]
Fix in #157
